AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  get-index

  Sample SAM Template for get-index

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120
    MemorySize: 512

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get-index-lambda/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64

  BedrockInvokePermission:
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref ApiFunction
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com
      SourceArn: arn:aws:bedrock:us-east-1:743783005718:agent/*


  # BedrockInvokePermission:
  #   Type: AWS::Lambda::Permission 
  #   Properties:
  #     FunctionName: !Ref ApiFunction
  #     Effect: Allow
  #     Principal: 
  #       Service: bedrock.amazonaws.com
  #     Action: lambda:InvokeFunction
  #     Resource : !GetAtt ApiFunction.Arn
  #     Condition: 
  #       ArnLike:
  #         "aws:SourceArn": "arn:aws:bedrock:us-east-1:743783005718:agent/*"



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ApiFunction:
    Description: "Get Index Lambda Function ARN"
    Value: !GetAtt ApiFunction.Arn
  ApiFunctionIamRole:
    Description: "Implicit IAM Role created for Api function"
    Value: !GetAtt ApiFunctionRole.Arn
